### ISSUE TITLE
Can't get the results reported in the paper

### ISSUE THREAD

**Issue by ITBeyond1230** [EricArazo/PseudoLabeling#1]
Hi, I run the scripts RunScripts_SOTA1000.sh for cifar10, but the final accuracy is 71.62%(i.e. error 28.37%), which is not matching your reported results. Can you give some suggestions about it? Thank you !

**Comment by DiegoOrtego** [comment]
Hi! We've found an error in the code that we uploaded (we removed by accident one line when cleaning the code) and unlabeled samples are not using the network prediction, but a zeros vector. Eric will update the code as soon as possible (1-2 days maximum). We will let you know!

**Comment by EricArazo** [comment]
Hello, I just fixed the code.  Now it is working and the results are as reported. Thank you for noticing it and feel free to contact us for any question.
