### ISSUE TITLE
miniImageNet experiments?

### ISSUE THREAD

**Issue by zijian-hu** [EricArazo/PseudoLabeling#5]
Dear Authors,

It seems like **miniImageNet** experiments are not included in the repo. It would be very helpful if we can have access to the **miniImageNet** experiments.

Do you plan to release the **miniImageNet** code?

Thank you!

**Comment by EricArazo** [comment]
Hello zijian-hu,

Yes, we plan to release the code in the coming weeks. 

Best,
Eric

**Comment by EricArazo** [comment]
Hello zijian-hu,

We just uploaded the experiments with miniImagenet.
Thank you for your interest in our work!

Best regards,
Eric
